
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod
tasks:
  - before: ./scripts/gitpod-before.sh
  - init: pnpm install
    command: pnpm build

image: nberlette/gitpod-enhanced
vscode:
  extensions:
    - davidanson.vscode-markdownlint
    - rvest.vs-code-prettier-eslint
    - dbaeumer.vscode-eslint
