name: Integration Tests

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        id: success
        with:
          file: tests/fixtures/gradle.properties
          property: pluginName
      - run: '[[ "TownyPlus" == "${{ steps.success.outputs.value }}" ]]'

      - uses: ./
        id: default
        with:
          file: tests/fixtures/gradle.properties
          property: version
      - run: '[[ "1.1.0-alpha.16" == "${{ steps.default.outputs.value }}" ]]'

      - uses: ./
        id: unexisting-property
        with:
          file: tests/fixtures/gradle.properties
          property: name
          default: Anakin Skywalker
      - run: '[[ "Anakin Skywalker" == "${{ steps.unexisting-property.outputs.value }}" ]]'
      - uses: ./
        id: glob-test
        with:
          file: "**/*.properties"
          property: author
          default: Anakin Skywalker
      - run: '[[ "Anakin Skywalker" == "${{ steps.glob-test.outputs.value }}" ]]'
      - uses: ./
        id: glob-test2
        with:
          file: "**/gradle.properties"
          property: author
          default: Anakin Skywalker
      - run: '[[ "Romvnly" == "${{ steps.glob-test2.outputs.value }}" ]]'

      - uses: ./
        id: all
        with:
          file: tests/fixtures/gradle.properties
          all: true
      - run: '[[ "1.1.0-alpha.16" == "${{ steps.all.outputs.version }}" ]]'
      - run: '[[ "1.16" == "${{ steps.all.outputs.apiVersion }}" ]]'
      - run: '[[ "TownyPlus" == "${{ steps.all.outputs.pluginName }}" ]]'

      - uses: ./
        id: failure
        with:
          file: tests/fixtures/da.properties
          property: name
        continue-on-error: true
      - run: '[[ "failure" == "${{ steps.failure.outcome }}" ]]'
      - uses: ./
        id: failure2
        with:
          file: tests/fixtures/trash.properties
          property: good
        continue-on-error: true
      - run: '[[ "failure" == "${{ steps.failure2.outcome }}" ]]'